//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cluster")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    pub face_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::face::Entity",
        from = "Column::FaceId",
        to = "super::face::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Face,
}

impl Related<super::face::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Face.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
