//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cluster")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: String,
    pub face_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::face::Entity",
        from = "Column::FaceId",
        to = "super::face::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Face,
    #[sea_orm(has_many = "super::media_face::Entity")]
    MediaFace,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::face::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Face.def()
    }
}

impl Related<super::media_face::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFace.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
