//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "face")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    pub name: String,
    pub featured_photo_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_face::Entity",
        from = "Column::FeaturedPhotoId",
        to = "super::media_face::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MediaFace,
}

impl Related<super::media_face::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
