name: Build Docker Images for AMD64

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-publish-amd64:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 6000:5000

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build Base Image Locally
        uses: docker/build-push-action@v6
        with:
          context: ./docker/base
          push: true
          tags: |
            localhost:6000/chronolens/base:${{ github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name }}
          platforms: linux/amd64

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/api
          push: true
          tags: |
            ghcr.io/chronolens/chronolens/api:${{ github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name }}
          platforms: linux/amd64

      - name: Build and Push Preview Image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/preview
          push: true
          tags: |
            ghcr.io/chronolens/chronolens/preview:${{ github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name }}
          platforms: linux/amd64

