name: Build and Publish Docker Images

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tag Based on Branch
        id: image-tag
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "tag=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
          fi

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/base
          push: true
          tags: |
            ghcr.io/chronolens/chronolens-base:${{ github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name }}  # Pass branch name as a build argument
          platforms: linux/amd64,linux/arm64

      - name: Build and Push API Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/api
          push: true
          tags: |
            ghcr.io/chronolens/chronolens-api:${{ env.tag }}
          build-args: |
            TAG=${{ github.ref_name }}  # Pass branch name as a build argument
          platforms: linux/amd64,linux/arm64

      - name: Build and Push Preview Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/preview
          push: true
          tags: |
            ghcr.io/chronolens/chronolens-preview:${{ env.tag }}
          build-args: |
            TAG=${{ github.ref_name }}  # Pass branch name as a build argument
          platforms: linux/amd64,linux/arm64
